// Generated by Eris
#include "../src/eris.h"
int main(int argc, char** argv) {
for(ErisVal i = ErisVal::make_num(0); ((i < ErisVal::make_num(10))).b; (i = (i + ErisVal::make_num(1)))) {
}
    return 0;
}