// Generated by Eris
#include "../src/eris.h"
int main(int argc, char** argv) {
ErisVal f = (ErisVal::make_func([&](const std::vector<ErisVal>& args) {
ErisVal x = args.at(0);
ErisVal y = args.at(1);
return (x * y);
}));
    return 0;
}