// Generated by Eris
#include "../src/eris.h"
int main(int argc, char** argv) {
FileSystem.o->get("write")({FileSystem,ErisVal::make_str("test/test.txt"),ErisVal::make_str("Hello world!")});
System.o->get("print")({System,FileSystem.o->get("read")({FileSystem,ErisVal::make_str("test/test.txt")})});
    return 0;
}