(* Helpers *)
any character = ? All visible characters ?;
whitespace = " " | "\n" | "\t";
letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" ;
dec digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
hex digit = dec digit | "A" | "B" | "C" | "D" | "E" | "F" | "a" | "b" | "c" | "d" | "e" | "f";

(* Main rules *)
dec int = dec digit, { dec digit };
hex int = "0x", hex digit, { hex digit };
dec byte = dec int, ("Y" | "y");
hex byte = hex int, ("Y" | "y");
float = dec int, ".", [ dec int ];
string = '"', { any character - '"' }, '"';
identifier = ( letter, { letter | digit | "_" } ) - keyword;
keyword = "null" | "true" | "false" | "var" | "if" | "else" | "for" | "while" | "switch" | "case" | "def" | "lambda" | "return" | "class" | "extends";