// Generated by Eris
#include "./include/eris.h"
int main(int argc, char** argv) {
ErisVal fac = ErisVal::make_func([&](const std::vector<ErisVal>& args) {
ErisVal x = args.at(0);
{
if(((x == ErisVal::make_num(0))).b) {
return ErisVal::make_num(1);
} else {
return (x * fac({(x - ErisVal::make_num(1))}));
}
}
return ErisVal::make_nil();
});
System.o->get("print")({System,fac({ErisVal::make_num(5)})});
    return 0;
}