// Generated by Eris
#include "../src/eris.h"
int main(int argc, char** argv) {
ErisVal factorial = ErisVal::make_func([&](const std::vector<ErisVal>& args) {
ErisVal x = args.at(0);
{
if(((x <= ErisVal::make_num(1))).b) {
return ErisVal::make_num(1);
} else {
return (x * factorial({(x - ErisVal::make_num(1))}));
}
}
return ErisVal::make_nil();
});
System.o->get("print")({System,factorial({ErisVal::make_num(5)})});
    return 0;
}