<expr> ::= <term> | <expr> (<ADD> | <SUB>) <term>
<term> ::= <factor> | <term> (<MUL> | <DIV>) <factor>
<factor> ::= <NUMBER>
<OPT-WHITESPACE> ::= "" | (" " | "\n") <OPT-WHITESPACE>
<OPT-WHITESPACE> ::= "" | (" " | "\n") <OPT-WHITESPACE>