<expr> ::= <term> | <expr> <ADD> <factor> | expr <SUB> factor
<term> ::= <factor> | <term> <MUL> <factor> | term <DIV> factor
<factor> ::= <NUMBER>
<NUMBER> ::= <NUMBER>

<OPT-WHITESPACE> ::= "" | (" " | "\n") <OPT-WHITESPACE>
