#include <iostream>
#include <string>
#include <sstream>
#include <set>
#include "node.h"
#include "transpiler.h"

namespace eris {
    Transpiler::Transpiler(const std::string& filename)
        : filename(filename), included_headers({ "\"../src/eris.h\"" }) {
    }

    void Transpiler::visit(Node* node) {
        switch (node->kind()) {
        case NodeKind::NIL:
            return visit(static_cast<NilNode*>(node));
        case NodeKind::NUMBER:
            return visit(static_cast<NumberNode*>(node));
        case NodeKind::TRUE:
            return visit(static_cast<TrueNode*>(node));
        case NodeKind::FALSE:
            return visit(static_cast<FalseNode*>(node));
        case NodeKind::CHAR:
            return visit(static_cast<CharNode*>(node));
        case NodeKind::PAREN_EXPR:
            return visit(static_cast<ParenExprNode*>(node));
        case NodeKind::BINARY_EXPR:
            return visit(static_cast<BinaryExprNode*>(node));
        case NodeKind::EXPR_STMT:
            return visit(static_cast<ExprStmtNode*>(node));
        case NodeKind::VAR_DECL_STMT:
            return visit(static_cast<VarDeclStmtNode*>(node));
        case NodeKind::STMT_LIST:
            return visit(static_cast<StmtListNode*>(node));
        default:
            throw std::string(filename + ":" + std::to_string(node->line) + ": unknown AST node type");
        }
    }

    void Transpiler::visit(NilNode* node) {
        post_main_code << "ErisVal::make_nil()";
    }

    void Transpiler::visit(NumberNode* node) {
        post_main_code << "ErisVal::make_num(";
        post_main_code << node->val;
        post_main_code << ')';
    }

    void Transpiler::visit(TrueNode* node) {
        post_main_code << "ErisVal::make_bool(true)";
    }

    void Transpiler::visit(FalseNode* node) {
        post_main_code << "ErisVal::make_bool(false)";
    }

    void Transpiler::visit(CharNode* node) {
        post_main_code << "ErisVal::make_char('";
        post_main_code << node->val;
        post_main_code << "')";
    }

    void Transpiler::visit(ParenExprNode* node) {
        post_main_code << '(';
        visit(node->node.get());
        post_main_code << ')';
    }

    void Transpiler::visit(UnaryExprNode* node) {
        post_main_code << '(';
        post_main_code << node->op.val;
        visit(node->node.get());
        post_main_code << ')';
    }

    void Transpiler::visit(BinaryExprNode* node) {
        post_main_code << '(';
        visit(node->node_a.get());
        if(node->op.val == "^^") {
            post_main_code << "!=";
        } else {
        post_main_code << node->op.val;
        }
        visit(node->node_b.get());
        post_main_code << ')';
    }

    void Transpiler::visit(ExprStmtNode* node) {
        visit(node->node.get());
        post_main_code << ";\n";
    }

    void Transpiler::visit(VarDeclStmtNode* node) {
        post_main_code << "ErisVal ";
        post_main_code << node->name;
        post_main_code << '=';
        visit(node->val.get());
        post_main_code << ";\n";
    }

    void Transpiler::visit(StmtListNode* node) {
        for(std::shared_ptr<Node> stmt : node->stmts) {
            visit(stmt.get());
        }
    }

    std::string Transpiler::generate_code(Node* node) {
        visit(node);
        std::string code = "// Generated by Eris\n";
        for (const std::string& header : included_headers) {
            code += "#include " + header + "\n";
        }
        code += "int main(int argc, char** argv) {\n";
        code += post_main_code.str();
        code += "    return 0;\n}";
        return code;
    }
}; // namespace eris